from sqlalchemy import Column, Integer, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB
from app.db.base import Base


class Trip(Base):
    __tablename__ = "trips"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    region = Column(String, nullable=False)       # e.g. South India
    base_city = Column(String, nullable=False)    # e.g. Bangalore

    constraints = Column(JSONB, nullable=False)   # budget, days, pace
    trip_graph = Column(JSONB, nullable=True)     # GENERATED BY AGENTS
