"""Add comfort_radius to itinerary

Revision ID: 1808f189740a
Revises: 
Create Date: 2026-03-09 08:30:12.201616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1808f189740a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('comfort_radius', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'plan_feedback', 'generated_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_feedback', type_='foreignkey')
    op.drop_column('itineraries', 'comfort_radius')
    # ### end Alembic commands ###
